import type {Metadata} from "next";
import "./globals.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import localFont from "next/font/local";
import Header from "@/components/layout/header/Header";
import Footer from "@/components/layout/footer/Footer";
import {SessionProvider} from "next-auth/react";

const pretendard = localFont({
	src: "./fonts/PretendardStdVariable.woff2",
	display: "swap",
	weight: "45 920",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({children}: LayoutProps<"/">) {
	return (
		<html lang="ko" className={pretendard.className} suppressHydrationWarning>
			<head>
				<script
					dangerouslySetInnerHTML={{
						__html: `(function(){
					try {
						const value = localStorage.getItem("color-theme");
						if(value === "dark" || value === "light") {
							document.documentElement.dataset.theme = value;
						}
					} catch (e) {}
					})()`,
					}}
				/>
			</head>

			<body>
				<SessionProvider>
					<Header />
					{children}
					<Footer />
				</SessionProvider>
			</body>
		</html>
	);
}
