import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

import localFont from "next/font/local";
import Header from "./component/section-tag/header";
import Footer from "./component/section-tag/footer";

const pretendard = localFont({
    src: "./fonts/PretendardStdVariable.woff2",
    display: "swap",
    weight: "45 920",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
        <html lang="ko" className={pretendard.className}>
            <body>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
